apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carbonetes-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carbonetes-operator
subjects:
- kind: ServiceAccount
  name: carbonetes-operator
